services:
  - type: web
    name: chain-reg-api-server
    env: rust
    repo: https://github.com/system-zero-labs/chain-registry-api
    plan: free
    region: oregon
    branch: main
    numInstances: 1
#    healthCheckPath: /v1/mainnet/chains # TODO: add me
#    scaling:
#      minInstances: 1
#      maxInstances: 1
    buildCommand: cargo build --release
    startCommand: cargo run --release serve
    domains:
      - chainregistry.xyz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chain-reg-api-db
          property: connectionString

  - type: cron
    name: chain-reg-api-hydrate
    env: rust
    schedule: "*/5 * * * *"
    buildCommand: cargo build --release
    startCommand: cargo run --release hydrate
    repo: https://github.com/system-zero-labs/chain-registry-api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chain-reg-api-db
          property: connectionString

  - type: cron
    name: chain-reg-api-liveness # TODO: eventually refactor to a background worker
    env: rust
    schedule: "*/6 * * * *"
    buildCommand: cargo build --release
    startCommand: cargo run --release liveness
    repo: https://github.com/system-zero-labs/chain-registry-api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chain-reg-api-db
          property: connectionString

databases:
  - name: chain-reg-api-db
    plan: starter
    databaseName: chain_reg_prod
    region: oregon
    user: chain_reg_admin
    ipAllowList: [] # only allow internal connections
